// In this file you can specify the trial data for your experiment


const trials_practice = {
    key_press: [
        {
            picture: "images/practice/13_50_different.jpg",
            picture_nr: 13,
            degree_rott: 50,
            expected: 'different',
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',

        },
        {
            picture: "images/practice/13_50_same.jpg",
            picture_nr: 13,
            degree_rott: 50,
            expected: 'same',
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/practice/13_150_same.jpg",
            picture_nr: 13,
            expected: "same",
            degree_rott: 150,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/practice/13_150_different.jpg",
            picture_nr: 13,
            expected: "different",
            degree_rott: 150,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/practice/14_50_same.jpg",
            picture_nr: 14,
            expected: "same",
            degree_rott: 50,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/practice/14_50_different.jpg",
            picture_nr: 14,
            expected: "different",
            degree_rott: 50,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/practice/14_150_same.jpg",
            picture_nr: 14,
            expected: "same",
            degree_rott: 150,key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/practice/14_150_different.jpg",
            picture_nr: 14,
            expected: "different",
            degree_rott: 150,key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/practice/15_50_same.jpg",
            picture_nr: 15,
            expected: "same",
            degree_rott: 50,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/practice/15_50_different.jpg",
            picture_nr: 15,
            expected: "different",
            degree_rott: 50,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/practice/15_150_same.jpg",
            picture_nr: 15,
            expected: "same",
            degree_rott: 150,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/practice/15_150_different.jpg",
            picture_nr: 15,
            expected: "different",
            degree_rott: 150,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
    ],
};

const main_trials = {
    key_press: [
        {
            picture: "images/main/1_50_same.jpg",
            picture_nr: 1,
            expected: "same",
            degree_rot: 50,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',

        },
        {
            picture: "images/main/1_50_different.jpg",
            picture_nr: 1,
            expected: "different",
            degree_rot: 50,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',

        },
        {
            picture: "images/main/1_150_same.jpg",
            picture_nr: 1,
            expected: "same",
            degree_rot: 150,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/main/1_150_different.jpg",
            picture_nr: 1,
            expected: "different",
            degree_rot: 150,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/main/2_50_same.jpg",
            picture_nr: 2,
            expected: "same",
            degree_rot: 50,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/main/2_50_different.jpg",
            picture_nr: 2,
            expected: "different",
            degree_rot: 50,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/main/2_150_same.jpg",
            picture_nr: 2,
            expected: "same",
            degree_rot: 150,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/main/2_150_different.jpg",
            picture_nr: 2,
            expected: "different",
            degree_rot: 150,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },

        {
            picture: "images/main/3_50_same.jpg",
            picture_nr: 3,
            expected: "same",
            degree_rot: 50,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/main/3_50_different.jpg",
            picture_nr: 3,
            expected: "different",
            degree_rot: 50,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/main/3_150_same.jpg",
            picture_nr: 3,
            expected: "same",
            degree_rot: 150,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/main/3_150_different.jpg",
            picture_nr: 3,
            expected: "different",
            degree_rot: 150,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },

        {
            picture: "images/main/4_50_same.jpg",
            picture_nr: 4,
            expected: "same",
            degree_rot: 50,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/main/4_50_different.jpg",
            picture_nr: 4,
            expected: "different",
            degree_rot: 50,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/main/4_150_same.jpg",
            picture_nr: 4,
            expected: "same",
            degree_rot: 150,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/main/4_150_different.jpg",
            picture_nr: 4,
            expected: "different",
            degree_rot: 150,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },

        {
            picture: "images/main/5_50_same.jpg",
            picture_nr: 5,
            expected: "same",
            degree_rot: 50,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/main/5_50_different.jpg",
            picture_nr: 5,
            expected: "different",
            degree_rot: 50,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/main/5_150_same.jpg",
            picture_nr: 5,
            expected: "same",
            degree_rot: 150,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/main/5_150_different.jpg",
            picture_nr: 5,
            expected: "different",
            degree_rot: 150,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/main/6_50_same.jpg",
            picture_nr: 6,
            expected: "same",
            degree_rot: 50,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/main/6_50_different.jpg",
            picture_nr: 6,
            expected: "different",
            degree_rot: 50,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/main/6_150_same.jpg",
            picture_nr: 6,
            expected: "same",
            degree_rot: 150,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/main/6_150_different.jpg",
            picture_nr: 6,
            expected: "different",
            degree_rot: 150,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },

        {
            picture: "images/main/7_50_same.jpg",
            picture_nr: 7,
            expected: "same",
            degree_rot: 50,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/main/7_50_different.jpg",
            picture_nr: 7,
            expected: "different",
            degree_rot: 50,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/main/7_150_same.jpg",
            picture_nr: 7,
            expected: "same",
            degree_rot: 150,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/main/7_150_different.jpg",
            picture_nr: 7,
            expected: "different",
            degree_rot: 150,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },

        {
            picture: "images/main/8_50_same.jpg",
            picture_nr: 8,
            expected: "same",
            degree_rot: 50,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/main/8_50_different.jpg",
            picture_nr: 8,
            expected: "different",
            degree_rot: 50,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/main/8_150_same.jpg",
            picture_nr: 8,
            expected: "same",
            degree_rot: 150,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/main/8_150_different.jpg",
            picture_nr: 8,
            expected: "different",
            degree_rot: 150,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },

        {
            picture: "images/main/9_50_same.jpg",
            picture_nr: 9,
            expected: "same",
            degree_rot: 50,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/main/9_50_different.jpg",
            picture_nr: 9,
            expected: "different",
            degree_rot: 50,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/main/9_150_same.jpg",
            picture_nr: 9,
            expected: "same",
            degree_rot: 150,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/main/9_150_different.jpg",
            picture_nr: 9,
            expected: "different",
            degree_rot: 150,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/main/10_50_same.jpg",
            picture_nr: 10,
            expected: "same",
            degree_rot: 50,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/main/10_50_different.jpg",
            picture_nr: 10,
            expected: "different",
            degree_rot: 50,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/main/10_150_same.jpg",
            picture_nr: 10,
            expected: "same",
            degree_rot: 150,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/main/10_150_different.jpg",
            picture_nr: 10,
            expected: "different",
            degree_rot: 150,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/main/11_50_same.jpg",
            picture_nr: 11,
            expected: "same",
            degree_rot: 50,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/main/11_50_different.jpg",
            picture_nr: 11,
            expected: "different",
            degree_rot: 50,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/main/11_150_same.jpg",
            picture_nr: 11,
            expected: "same",
            degree_rot: 150,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/main/11_150_different.jpg",
            picture_nr: 11,
            expected: "different",
            degree_rot: 150,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/main/12_50_same.jpg",
            picture_nr: 12,
            expected: "same",
            degree_rot: 50,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/main/12_50_different.jpg",
            picture_nr: 12,
            expected: "different",
            degree_rot: 50,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/main/12_150_same.jpg",
            picture_nr: 12,
            expected: "same",
            degree_rot: 150,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
        {
            picture: "images/main/12_150_different.jpg",
            picture_nr: 12,
            expected: "different",
            degree_rot: 150,
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
        },
    ],
};
